#!/bin/bash

echo "==================================="
echo "WeLearn Downloader - Feature Demo"
echo "==================================="
echo ""
echo "This demo shows the new features:"
echo "1. Interactive file selection menu"
echo "2. Tree/List view of files"
echo "3. Custom download directory"
echo "4. Select specific files to download"
echo ""
echo "The application now provides two modes:"
echo "  Mode 1: Download all files (original behavior)"
echo "  Mode 2: Interactive file selection (NEW)"
echo ""
echo "In Mode 2, you can:"
echo "  - View files in tree or list format"
echo "  - Choose download directory"
echo "  - Select 'all' or specific file numbers"
echo "  - Example: Enter '1,3,5' to download files 1, 3, and 5"
echo ""
echo "Build status:"
make cli 2>&1 | grep -E "(built successfully|error)"
echo ""
echo "To run the application:"
echo "  ./welearn_cli"
echo ""
echo "Note: Actual login requires valid WeLearn credentials"
